<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRzy5gxt\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRzy5gxt/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerRzy5gxt.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerRzy5gxt\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerRzy5gxt\appProdProjectContainer([
    'container.build_hash' => 'Rzy5gxt',
    'container.build_id' => 'b760d6a2',
    'container.build_time' => 1655375496,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRzy5gxt');
